// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygjglcgkjsvrwmjnfvlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnamdsY2dranN2cndtam5mdmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzgwOTAsImV4cCI6MjA1ODcxNDA5MH0.RabLekYOnJoI00jg-7u4r7QsR0q8nOZVW0S6PCCvGpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);